openapi: 3.0.2
info:
  title: EPIC API
  version: ''
paths:
  /api/customer/:
    get:
      operationId: listCustomers
      description: Return the list of customers
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
      - crm
    post:
      operationId: createCustomer
      description: add a customer.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
      - crm
  /api/customer/{id}/:
    get:
      operationId: retrieveCustomer
      description: Return a customer .
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
      - crm
    put:
      operationId: updateCustomer
      description: update a customer
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
      - crm
    patch:
      operationId: partialUpdateCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
      - crm
    delete:
      operationId: destroyCustomer
      description: delete a customer
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - customer
      - crm
  /api/contract/:
    get:
      operationId: listContracts
      description: Return the list of contracts
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/contract'
          description: ''
      tags:
      - contract
      - crm
    post:
      operationId: createContract
      description: add a contract.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/contract'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/contract'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contract'
          description: ''
      tags:
      - contract
      - crm
  /api/contract/{id}/:
    get:
      operationId: retrieveContract
      description: Return a contract .
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contract'
          description: ''
      tags:
      - contract
      - crm
    put:
      operationId: updateContract
      description: update a contract
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/contract'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/contract'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contract'
          description: ''
      tags:
      - contract
      - crm
    patch:
      operationId: partialUpdateContract
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/contract'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/contract'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contract'
          description: ''
      tags:
      - contract
      - crm
    delete:
      operationId: destroyContract
      description: delete a contract
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - contract
      - crm
  /api/event/:
    get:
      operationId: listevents
      description: Return the list of events
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/event'
          description: ''
      tags:
      - event
      - crm
    post:
      operationId: createevent
      description: add an event.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/event'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/event'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
          description: ''
      tags:
      - event
      - crm
  /api/event/{id}/:
    get:
      operationId: retrieveevent
      description: Return an event.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
          description: ''
      tags:
      - event
      - crm
    put:
      operationId: updateevent
      description: update an event.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/event'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/event'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
          description: ''
      tags:
      - event
      - crm
    patch:
      operationId: partialUpdateevent
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/event'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/event'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
          description: ''
      tags:
      - event
      - crm
    delete:
      operationId: destroyevent
      description: delete an event.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - event
      - crm
  /api/token/refresh/:
    post:
      operationId: createTokenRefresh
      description: 'Takes a refresh type JSON web token and returns an access type
        JSON web

        token if the refresh token is valid.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
      tags:
      - api
  /api/login/:
    post:
      operationId: createTokenObtainPair
      description: 'Takes a set of user credentials and returns an access and refresh
        JSON web

        token pair to prove the authentication of those credentials.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
      tags:
      - api
components:
  schemas:
    Customer:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 25
        last_name:
          type: string
          maxLength: 25
        sales_contact:
          type: string
        email:
          type: string
          nullable: true
          maxLength: 100
      required:
      - first_name
      - last_name
      - sales_contact
    contract:
      type: object
      properties:
        sales_contact:
          type: string
        customer:
          type: string
          readOnly: true
        status:
          type: string
          readOnly: true
        amount:
          type: number
        payment_due:
          type: string
          format: date-time
          nullable: true
      required:
      - sales_contact
    event:
      type: object
      properties:
        support_contact:
          type: string
        customer__last_name:
          type: string
          readOnly: true
        customer__email:
          type: string
          readOnly: true
        status:
          type: string
          readOnly: true
        attendees:
          type: integer
          maximum: 2147483647
          minimum: 0
        event_date:
          type: string
          format: date-time
          nullable: true
      required:
      - support_contact
    TokenRefresh:
      type: object
      properties:
        refresh:
          type: string
        access:
          type: string
          readOnly: true
      required:
      - refresh
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - username
      - password
