# Generated by Django 4.1.1 on 2022-11-02 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0006_alter_contract_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="amount",
            field=models.FloatField(default=0, help_text="contract's amount"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="contract's customer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_to",
                to="crm.customer",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="contract's creation date"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="contract's update date"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_due",
            field=models.DateTimeField(
                blank=True, help_text="contract's paiement due date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="sales_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="contract's sale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("S", "Sign"), ("QS", "Quote sent"), ("P", "In progress")],
                default="P",
                help_text="contract's status",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="customer's company name",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="customer's creation date"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="customer's update date"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(
                blank=True, help_text="customer's email", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(help_text="customer's firstname", max_length=25),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(help_text="customer's lastname", max_length=25),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.EmailField(
                blank=True, help_text="customer's mobile", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True, help_text="customer's phone", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sales_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="customer's sale contact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.PositiveIntegerField(
                default=0, help_text="event's number of attendees"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="event's customer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organise",
                to="crm.customer",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="event's creation date"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, help_text="event's update date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(blank=True, help_text="event's date", null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True, help_text="event's note", null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="event's status",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.status",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="support_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="event's support",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
