# Generated by Django 4.1.1 on 2022-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_contract_customer_alter_event_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("S", "Sign"), ("QS", "Quote sent"), ("P", "In progress")],
                default="P",
                help_text="This field is used to categorize the project. Use, S=>Sign, QS=>Quote sent, P=>In progress",
                max_length=3,
            ),
        ),
    ]
