# Generated by Django 4.1.1 on 2022-09-20 09:43
from django.db import migrations


def add_groups(apps, schema_editors):

    Group_ = apps.get_model("auth", "Group")
    Group_.objects.get_or_create(name="management_team")
    Group_.objects.get_or_create(name="sales_team")
    Group_.objects.get_or_create(name="support_team")


def remove_group(apps, schema_editors):
    Group_ = apps.get_model("auth", "Group")
    Group_.objects.filter(name__in=["management_team", "sales_team", "support_team"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_groups, remove_group)]
